### ISSUE TITLE
about train data

### ISSUE THREAD

**Issue by cqray1990** [Rid7/Table-OCR#3]
which train data you use? labeling by yourself or some public data? if public data,which data you use?
Thank you

**Comment by Rid7** [comment]
I customized my data with PDF files and digital scan files.  Some public datasets like SciSTR, tablebank, PubTabNet would be helpful while they are quite neat, I think blended them with noise should be a  process make sense.

**Comment by cqray1990** [comment]
how did you label your data, and what label format is like?
thank you so much

**Comment by cqray1990** [comment]
the project can not be trained? it is not complete

**Comment by Rid7** [comment]
> the project can not be trained? it is not complete

Actually, I do not think open my train code is necessary since I can't open my datasets and it is far from good right now. This repo is more significant in how to process the table cells after you get the lines. If you are interested in training,  you could find some reference in some road detection examples, they are quite similar.
